#!/usr/bin/env bash
#This script whose function is to ping an IP address passed as an argument

if [ $# -eq 0 ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address"

exit $?
