#!/usr/bin/env bash
#This script whose function is to ping an IP address passed as an argument

if [ $# -eq 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$ip_address"
fi
